# Generated by Django 5.2.8 on 2025-11-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('rollno', 'student_class')},
        ),
    ]
